### ISSUE TITLE
Is this paper available?

### ISSUE THREAD

**Issue by morte2025** [nubot-nudt/ElC-OIS#1]

**Comment by dwbzxc** [comment]
The paper is under review for now.

**Comment by morte2025** [comment]
Alright, maybe you can put it on ArXiv.

**Comment by dwbzxc** [comment]
Yes, we will publish a preprint later.

**Comment by dwbzxc** [comment]
@HMX2013 Hi! The preprint of our paper is available in this [link](https://arxiv.org/pdf/2303.04351.pdf) now. Thanks for your attention!
