### ISSUE TITLE
About the Baidu cloud files.

### ISSUE THREAD

**Issue by kxxbeomjun** [nubot-nudt/ElC-OIS#3]
Hi, is there any other way getting tar zip files(60.6MB) that you linked to Baidu cloud?

Unfortunately, I don't have the Baidu account. And also when I try to make a account, it's not availabe other than China number.

**Comment by kxxbeomjun** [comment]
Oh, I saw that you added Google onedrive link. Thank you :)

**Comment by dwbzxc** [comment]
Yep! We added an OneDrive link. Feel free to download it.
